name = "pwa-sharing"
main = "src/server/index.js"
compatibility_date = "2025-02-07"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[observability.logs]
enabled = true
