name: rebase-auto-update-branch

on:
  push:
    branches:
      - main

concurrency:
  group: "rebase"
  cancel-in-progress: true

jobs:
  rebase-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for rebase
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Rebase `auto-update` onto `main`
        run: |
          git checkout auto-update
          git rebase main

      - name: Push changes
        run: |
          git push origin auto-update --force-with-lease